language: node_js
node_js:
  - '8'
# before_install
# before
# before_script
script
  - echo "Hello World"
# after_success
# after_faliure
# after_script
# before_deploy
deploy:
  provider: pages
  skip_cleanup: true
#  deployment_branch: master
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
# after_deploy
# Test pull request merge, travis trigger
